---
apiVersion: catalog.opencenter.dev/v1alpha1
kind: ServiceEntry
name: longhorn
path: applications/base/services/longhorn
packaging: helmRepository
version: 1.12.1
namespace: longhorn-system
source:
  name: longhorn-repo
  url: https://charts.longhorn.io
description: Distributed block storage
blueprints:
  - name: minimal
    tier: recommended
  - name: enterprise
    tier: recommended
  - name: storage
    tier: recommended
renderOwner: renderCatalog
