apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - source.yaml
  - helmrelease.yaml
secretGenerator:
  - name: kured-values-base
    namespace: kured-system
    type: Opaque
    files:
      - values.yaml=helm-values/values-6.1.0.yaml
    options:
      disableNameSuffixHash: true
