---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: training-operator
  namespace: kubeflow-system
spec:
  releaseName: training-operator
  interval: 5m
  timeout: 10m
  driftDetection:
    mode: enabled
  install:
    remediation:
      retries: 3
      remediateLastFailure: true
  upgrade:
    remediation:
      retries: 0
      remediateLastFailure: false
  targetNamespace: kubeflow-system
  chart:
    spec:
      chart: kubeflow-trainer
      version: 0.0.1
      sourceRef:
        kind: HelmRepository
        name: kubeflow
        namespace: kubeflow-system
  valuesFrom:
    - kind: Secret
      name: training-operator-values-base
      valuesKey: values.yaml
    - kind: Secret
      name: training-operator-values-override
      valuesKey: override.yaml
      optional: true
