apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - source.yaml
  - helmrelease.yaml
secretGenerator:
  - name: ceph-csi-rbd-values-base
    namespace: ceph-csi
    type: Opaque
    files:
      - values.yaml=helm-values/values-3.17.0.yaml
    options:
      disableNameSuffixHash: true
