apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
    - namespace.yaml
    - source.yaml
    - helmrelease.yaml
secretGenerator:
    - name: nfd-values-base
      namespace: node-feature-discovery
      type: Opaque
      files:
        - values.yaml=helm-values/values-0.18.3.yaml
      options:
        disableNameSuffixHash: true
