apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - source.yaml
  - helmrelease.yaml
secretGenerator:
  - name: local-path-provisioner-values-base
    namespace: local-path-storage
    type: Opaque
    files:
      - values.yaml=helm-values/values-0.0.36.yaml
    options:
      disableNameSuffixHash: true
