apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
    - namespace.yaml
    - source.yaml
    - helmrelease-crds.yaml
    - helmrelease.yaml
secretGenerator:
    - name: calico-values-base
      namespace: tigera-operator
      type: Opaque
      files:
        - values.yaml=helm-values/values-v3.32.0.yaml
      options:
        disableNameSuffixHash: true
