# Default values for external-dns.
# Chart version: 1.20.0
# App version: v0.20.0

image:
  repository: registry.k8s.io/external-dns/external-dns
  pullPolicy: IfNotPresent

serviceAccount:
  create: true
  automountServiceAccountToken: true

rbac:
  create: true

deploymentStrategy:
  type: Recreate

podSecurityContext:
  runAsNonRoot: true
  fsGroup: 65534
  seccompProfile:
    type: RuntimeDefault

securityContext:
  privileged: false
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 65532
  runAsGroup: 65532
  capabilities:
    drop:
      - ALL

sources:
  - service
  - ingress

policy: upsert-only

registry: txt

logLevel: info
logFormat: text

interval: 1m

triggerLoopOnEvent: false

provider:
  name: aws

livenessProbe:
  httpGet:
    path: /healthz
    port: http
  initialDelaySeconds: 10
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 2
  successThreshold: 1

readinessProbe:
  httpGet:
    path: /healthz
    port: http
  initialDelaySeconds: 5
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 6
  successThreshold: 1

service:
  enabled: true
  port: 7979

serviceMonitor:
  enabled: false
