apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
    - namespace.yaml
    - source.yaml
    - helmrelease.yaml
secretGenerator:
    - name: redis-operator-values-base
      namespace: redis-operator
      type: Opaque
      files:
        - values.yaml=helm-values/values-0.25.0.yaml
      options:
        disableNameSuffixHash: true
